FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update

RUN apt-get install -y \
        python3 \
        python3-dev \
        python3-venv \
        net-tools \
        wget \
        vim \
        lsof \
        git \
        iputils-ping

RUN apt-get install -yqq --no-install-recommends locales
RUN apt-get install -y python3-pip

RUN localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LC_MESSAGES=en_US.UTF-8

RUN apt-get update
RUN rm -rf /var/lib/apt/lists/*


# Anaconda 설치
WORKDIR /tmp
COPY ./Anaconda3-2024.10-1-Linux-x86_64.sh /tmp
RUN bash Anaconda3-2024.10-1-Linux-x86_64.sh -b -p /root/anaconda3 && \
    rm Anaconda3-2024.10-1-Linux-x86_64.sh

# PATH 환경 변수 설정
ENV PATH="/root/anaconda3/bin:${PATH}"

RUN pip install --upgrade pip

# Conda 초기화 및 Jupyter 설치
RUN /root/anaconda3/bin/conda init bash && \
    /root/anaconda3/bin/conda install -y jupyterlab jupyter
RUN source ~/.bashrc
RUN /root/anaconda3/bin/jupyter notebook --generate-config
WORKDIR /root/.jupyter

RUN echo "c.ServerApp.password = u'argon2:$argon2id$v=19$m=10240,t=10,p=8$WYdzb4sS4rCJs+fOzrWgXA$jAQtyJzzfC9VhVl8Hs7AEImPFbKjQiFLSrdnv9JD+Qc'" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.ServerApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.ServerApp.notebook_dir = '/data'" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.ServerApp.allow_root = True" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.ServerApp.open_browser = False" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.ServerApp.terminado_settings = { 'shell_command': ['bash'] }" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.ServerApp.max_buffer_size = 1000000000000" >> /root/.jupyter/jupyter_notebook_config.py

# Python 심볼릭 링크 설정
RUN rm /usr/bin/python3 && ln -s /root/anaconda3/bin/python /usr/bin/python3 && \
    ln -s /usr/bin/python3 /usr/local/bin/python

# 작업 디렉토리 설정
WORKDIR /smwik

ENTRYPOINT ["/root/anaconda3/bin/jupyter", "lab"]